# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Avinash Prasad
email: avionmission@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to my blog.
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://avionmission.github.io" # the base hostname & protocol for your site, e.g. http://example.com

permalink: /:title/

twitter_username: avionmission
github_username:  avionmission
linkedin_username: avionmission
instagram_username: avionmission
youtube_username: AvinashPrasad

title-logo: /images/title-logo.png

author: Avinash Prasad

copyright: Avinash Prasad

show_excerpts: true

# Build settings
# [Removed minima theme as it is now a regular theme.]
# theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

defaults:
 # _posts
     - scope:
         path: ""
         type: posts
     values:
         autoads: true

# Google Analytics
google_analytics: UA-209087094-1


issues_repo: avionmission/blog
